Repository fnplus/interview-techdev-guide, pull requests merged in 2019-10, with the labels that each got.

#182 kruskals_algorithm.cpp: Add Kruskal's Algorithm
  Algorithms/Graph Traversal/Kruskals Algorithms/kruskals_algorithm.cpp
Labels: Hacktoberfest

#208 Added heapsort
  Algorithms/Searching & Sorting/Heap Sort/heap_sort.py
Labels: Hacktoberfest

#69 Create Selection Sort in C Issue # 31
  Selection Sort in C
Labels: Hacktoberfest

#115 bellman_ford_algorithm.cpp: Add Bellman Ford Algorithm
  Algorithms/Graph Traversal/Bellman Ford Algorithm/README.md
  Algorithms/Graph Traversal/Bellman Ford Algorithm/bellman_ford_algorithm.cpp
  Algorithms/Graph Traversal/Dijkstra's Algorithm/dijkstras_algorithm.cpp
Labels: Hacktoberfest

#118 bubble_sort.py Add BubbleSort Algorithm in Python
  Algorithms/Searching & Sorting/Bubble Sort/BubbleSort.py
Labels: Hacktoberfest

#123 Create singly_linked_list.py
  Data Structures/Singly Linked List/Python/singly_linked_list.py
Labels: Hacktoberfest

#131 Add Array and LinkedList Implementation of Queue in python.
  Data Structures/Queue/Python/Queue.py
Labels: Hacktoberfest

#134 PerfectNumber.c Add Math Algorithm
  Algorithms/Maths/Fibonacci series/C/Fibonacci_series.c
  Algorithms/Maths/Perfect number/C/PerfectNumber.c
  Algorithms/Tree Traversal/Binary Search Tree/Python/1.Search.py
  Algorithms/Tree Traversal/Binary Search Tree/Python/2.Insert.py
Labels: Hacktoberfest

#148 Added QuickSort in python
  Algorithms/Searching & Sorting/QuickSort/QuickSort.py
Labels: Hacktoberfest

#169 [Trie] - Trie implementation using map
  Data Structures/Trie/Trie.cpp
Labels: Hacktoberfest

#261 Revert "bellman_ford_algorithm.cpp: Add Bellman Ford Algorithm"
  Algorithms/Graph Traversal/Bellman Ford Algorithm/bellman_ford_algorithm.cpp
  Algorithms/Graph Traversal/Belmon Ford Algorithms/README.md
  Algorithms/Graph Traversal/Dijkstra's Algorithm/dijkstras_algorithm.cpp
Labels: Hacktoberfest

#164 binary_search_tree.py: Added Binary Search Tree Algorithm
  Algorithms/Tree/Binary Search Tree/Python/binary_search_tree.py
Labels: Hacktoberfest

#176 stack in python
  stack in python
Labels: Hacktoberfest

#187 add binary search algo in java
  Algorithms/Searching & Sorting/Binary Search/binary_search.java
Labels: Hacktoberfest

#189 add selection sort in java
  Algorithms/Searching & Sorting/Selection Sort/selection_sort.java
Labels: Hacktoberfest

#200 Segment tree : Updated
  Algorithms/Tree/Binary Search Tree/Python/deletion.py
  Algorithms/Tree/Segment Tree/Python/Segment_tree.py
Labels: Hacktoberfest

#215 added heap data structure in C++
  Data Structures/Heap/CPP/heap.cpp
Labels: Hacktoberfest

#246 Fibonacci series in Java added
  Algorithms/Fibonacci.java
Labels: Hacktoberfest

#247 c++ program to check armstrong number
  Algorithms/Maths/armstrong number/armstrong_numbers.cpp
  armstrong_numbers.cpp
Labels: Hacktoberfest

#257 Added Modular Exponentiation in C++.
  Algorithms/Maths/Modular Exponentiation/C/README.md
  Algorithms/Maths/Modular Exponentiation/CPP/ModularExponentiation.cpp
  Algorithms/Maths/Modular Exponentiation/Java/README.md
  Algorithms/Maths/Modular Exponentiation/Python/README.md
Labels: Hacktoberfest

#268 queue in cpp
  Algorithms/Maths/Pallindrome number/Java/Pallindrome_number.java
  Data Structures/Queue/CPP/Queue.cpp
Labels: Hacktoberfest

#263 floyd_warshall.cpp: Add Floyd Warshall Algorithm
  Algorithms/Graph Traversal/Floyd-Warshall Algorithm/floyd_warshall.cpp
Labels: Hacktoberfest

#284 MergeSort.cpp: Add Airbnb MergeSort Solution
  Company Specific Interview Questions/Airbnb/Solutions/Cpp/MergeSort.cpp
Labels: Hacktoberfest

#286 bst_height.cpp : Add height of binary search tree algorithm #266
  Algorithms/Tree/Height of the tree/CPP/bst_height.cpp
  Algorithms/Tree/Height of the tree/CPP/readme.md
Labels: Hacktoberfest

#288 Added a naive implementation of Chinese Remainder Theorem
  .DS_Store
  Algorithms/.DS_Store
  Algorithms/Maths/.DS_Store
  Algorithms/Maths/Chinese_Remainder_Theorem/CPP/chinese_remainder_theorem.cpp
Labels: Hacktoberfest

#296 adds kadane's algo in java
  Algorithms/Arrays/Kadane/Kadane_algo.java
Labels: Hacktoberfest

#301 Google Word Sequence CPP Solution added
  Company Specific Interview Questions/Google/Solutions/Cpp/Word_Break.cpp
Labels: Hacktoberfest

#305 to find first N pure numbers
  Algorithms/Maths/Perfect Number/Java/PerfectNumber.java
  Data Structures/Queue/Python/queue.py
Labels: Hacktoberfest

#311 [Algorithm] Perfect number [Java]
  Algorithms/Maths/Perfect number/Java/PerfectNumber.java
Labels: Hacktoberfest

#313 [Algorithm] DP - Edit Distance [Python]
  Algorithms/Dynamic Programming/edit_distance.py
Labels: Hacktoberfest

#315 added heap sort in C++
  Algorithms/Searching & Sorting/Heap Sort/heap_sort.cpp
Labels: Hacktoberfest

#322 Add bubble sort in C#
  Algorithms/Searching & Sorting/Bubble Sort/bubble_sort.cs
Labels: Hacktoberfest

#324 [Algorithm] Sum of Subset [Java]
  Algorithms/sumofsubset.java
Labels: Hacktoberfest

#325 Added a simple singly linked list example
  Data Structures/Singly Linked List/C/singlylinkedlist.c
Labels: Hacktoberfest

#318 Added Heapsort implementation in Java (issue #307)
  Algorithms/Searching & Sorting/Heap Sort/HeapSort.java
Labels: Hacktoberfest

#283 Added python implementation of doubly & circular linked list
  Data Structures/Circular Linked List/Python/circular_linked_list.py
  Data Structures/Doubly Linked List/Python/doubly_linked_list.py
Labels: Hacktoberfest

#308 [Data Structure] Circular Linked List [Python]
  Data Structures/Circular Linked List/Python/circularlinkedlist.py
Labels: Hacktoberfest

#82 selection sort created in java
  Algorithms/Searching & Sorting/Selection Sort/SelectionSort.java
Labels: Hacktoberfest

#132 Dijkstra
  Algorithms/Graphs/Dijkstra's Algorithm/Java/Dijkstra.java
  Algorithms/Maths/Pallindrome number/Java/palindrome.java
Labels: Hacktoberfest

#350 Fractional_Knapsack_Problem.java: Implement Fractional Knapsack Probl…
  Algorithms/Dynamic Programming/Fractional_Knapsack_Problem.java
Labels: Hacktoberfest

#289 COMPUTATIONAL GEOMETRY
  Algorithms/COMPUTATIONAL_GEOMETRY.md
  Algorithms/COMPUTATIONAL_GEOMETRY.py
  Algorithms/sieve.md
  Algorithms/sieve.py
Labels: Hacktoberfest

#78 Create insertion_sort.java
  Algorithms/Searching & Sorting/Insertion Sort/insertion_sort.java
Labels: Hacktoberfest

#79 Create insertion_sort.c
  Algorithms/Searching & Sorting/Insertion Sort/insertion_sort.c
Labels: Hacktoberfest

#80 Create quick_sort.py
  Algorithms/Searching & Sorting/QuickSort/quick_sort.py
Labels: Hacktoberfest

#291 a more thorough implementation of perfect numbers
  Algorithms/Maths/Perfect number/Python/Perfect_Number.py
  README.md
Labels: Hacktoberfest

#138 perfect.py: Added example of Perfect Number for Python
  Algorithms/Maths/Perfect Number/Python/perfect.py
Labels: Hacktoberfest

#166 Palindrome for a sentence
  Algorithms/Maths/Pallindrome number/Java/Pallindrome_string.java
Labels: Hacktoberfest

#180 Binary Search Tree in Python
  Algorithms/Tree/Binary Search Tree/Python/bst.py
Labels: Hacktoberfest, duplicate

#254 added base conversion program in c
  Algorithms/Maths/Base Conversion/C/base_conversion.c
Labels: Hacktoberfest

#364 added logic for Magic number
  Algorithms/Maths/Magic Number/Nodejs/MagicNumber.js
Labels: Hacktoberfest

#297 Add Binary Search Iterative & Recursive & Insertion Sort - Java
  Algorithms/Searching & Sorting/Binary Search/binary_search_iterative_recursive.java
  Algorithms/Searching & Sorting/Insertion Sort/Insertion_sort.java
Labels: Hacktoberfest

#306 Insertion sort python
  Algorithms/Searching & Sorting/Insertion Sort/InsertionSort.py
  README.md
Labels: Hacktoberfest

#332 Modular Exponentiation in C, Python and Java
  Algorithms/Maths/Modular Exponentiation/C/ModularExponentiation.c
  Algorithms/Maths/Modular Exponentiation/Java/ModularExponentiation.java
  Algorithms/Maths/Modular Exponentiation/Python/ModularExponentiation.py
Labels: Hacktoberfest

#339 Polite numbers in c++,python,java
  Algorithms/Maths/Polite number/polite_number.cpp
  Algorithms/Maths/Polite number/polite_number.java
  Algorithms/Maths/Polite number/polite_number.py
Labels: Hacktoberfest

#340 Detect cycle in a Graph
  Algorithms/Graphs/Cycle Detection/Directed Graph/CPP/cycle_detection_directed.cpp
  Algorithms/Graphs/Cycle Detection/Directed Graph/Java/cycle_detection_directed.java
  Algorithms/Graphs/Cycle Detection/Directed Graph/Python/cycle_detection_directed.py
  Algorithms/Graphs/Cycle Detection/Undirected Graph/C/cycle_detection_undirected.c
  Algorithms/Graphs/Cycle Detection/Undirected Graph/CPP/cycle_detection_undirected.cpp
  Algorithms/Graphs/Cycle Detection/Undirected Graph/Java/cycle_detection_undirected.java
  Algorithms/Graphs/Cycle Detection/Undirected Graph/Python/cycle_detection_undirected.py
Labels: Hacktoberfest

#342 KMP Algoritham to search substring
  Algorithms/String/KMP/CPP/KMP.cpp
Labels: Hacktoberfest

#343 [Algorithm] Insertion Sort [Python]
  Algorithms/Searching & Sorting/Insertion Sort/Insertionsort.py
Labels: Hacktoberfest

#344 simple_queue.py: Add Queue in Python
  Algorithms/Maths/Perfect Number/C/PerfectNumber.c
  Algorithms/Maths/Perfect Number/C/readme.md
  Algorithms/Maths/Perfect Number/CPP/readme.md
  Algorithms/Maths/Perfect Number/Java/PerfectNumber.java
  Algorithms/Maths/Perfect Number/Java/readme.md
  Algorithms/Maths/Perfect Number/Python/Perfect_Number.py
  Algorithms/Maths/Perfect Number/Python/readme.md
  Data Structures/Queue/Python/simple_queue.py
Labels: Hacktoberfest

#351 added bellman ford algo in java
  Algorithms/Graphs/Belmon Ford Algorithm/Java/bellman_ford_algo.java
Labels: Hacktoberfest

#352 Heap.java: Added Heap imlementation in java
  Data Structures/Heap/Java/Heap.java
Labels: Hacktoberfest

#368 Avl tree implementation in C++
  Algorithms/Tree/AVL Tree/CPP/avl.cpp
  Algorithms/Tree/AVL Tree/CPP/output.txt
  Algorithms/Tree/AVL Tree/CPP/readme.md
Labels: Hacktoberfest

#226 Added other code for dfs in python
  Algorithms/Graph Traversal/Depth First Search/dfs.py
Labels: Hacktoberfest, Not assigned to an issue

#394 implemetation of bfs
  Algorithms/Graphs/Implementation of BFS using adjacency matrix/c++/Implementation of BFS using adjacency matrix.cpp
  Algorithms/Maths/Sieve of Eratosthenes algorithm/cpp/Sieve of Eratosthenes algorithm.cpp
  Algorithms/Maths/Sieve of Eratosthenes algorithm/java/Sieve ofEratosthenes algorithm.java
Labels: Hacktoberfest

#465 Created Fibonacci Heap.
  Data Structures/Fibonacci Heap/Python/FibonacciHeap.py
Labels: Hacktoberfest

#458 BinarySearchTree.cpp: Add Airbnb BinarySearchTree
  Company Specific Interview Questions/Airbnb/Solutions/Cpp/BinarySearchTree.cpp
Labels: Hacktoberfest

#526 Tree PreOrder Traversal
  Algorithms/Tree Traversal/In-Order Traversal/inorder.c
  Algorithms/Tree Traversal/In-Order Traversal/inorder.cpp
  Algorithms/Tree Traversal/In-Order Traversal/inorder.js
  Algorithms/Tree Traversal/Post-Order Traversal/postorder.c
  Algorithms/Tree Traversal/Post-Order Traversal/postorder.cpp
  Algorithms/Tree Traversal/Post-Order Traversal/postorder.js
  Algorithms/Tree Traversal/Pre-Order Traversal/preorder.c
  Algorithms/Tree Traversal/Pre-Order Traversal/preorder.cpp
  Algorithms/Tree Traversal/Pre-Order Traversal/preorder.js
Labels: Hacktoberfest

#471 adjacency_matrix.py - Add adjacency matrix data structure
  Data Structures/Adjacency matrix/Python/adjacency_matrix.py
Labels: Hacktoberfest, enhancement

#476 Created Height of Tree [BST] in python and CPP
  Algorithms/Tree/Depth of the tree/CPP/height_of_bst.cpp
  Algorithms/Tree/Depth of the tree/Python/height_of_bst.py
Labels: Hacktoberfest

#477 Update knapsack with repition
  Algorithms/Dynamic Programming/Knapsack_with_repitition.cpp
Labels: Hacktoberfest

#108 Added insertion sort in C, Python and selection in C
  Algorithms/Searching & Sorting/Insertion Sort/insertion_sort.c
  Algorithms/Searching & Sorting/Insertion Sort/insertion_sort.py
  Algorithms/Searching & Sorting/Selection Sort/selection_sort.c
Labels: Conflict, Hacktoberfest

#109 [Algorithm] Fibonacci [JAVA]
  Algorithms/Maths/Fibonacci series/Java/Fibonacci.java
Labels: Conflict, Hacktoberfest

#110 [Algorithm] Palindrome [JAVA]
  Algorithms/Maths/Pallindrome number/Java/PallindromeNumber.java
Labels: Hacktoberfest, Not assigned to an issue

#111 [Algorithm] Palindrome [Python]
  Algorithms/Maths/Pallindrome number/Python/Palindrome.py
Labels: Hacktoberfest, Not assigned to an issue

#112 Added queue in java
  Data Structures/Queue/Java/Queue.java
Labels: Hacktoberfest, Not assigned to an issue

#113 Adding doubly linked list structure
  Data Structures/Doubly Linked List/C/Doubly linked list.c
Labels: Hacktoberfest, Not assigned to an issue

#117 heapsort
  Algorithms/Searching & Sorting/Heap Sort/heap
Labels: Hacktoberfest, Not assigned to an issue

#128 Added Binary Search In Ruby
  Algorithms/Searching & Sorting/Binary Search/Ruby/binary_search.rb
Labels: Hacktoberfest, Not assigned to an issue

#129 added bubble_sort in python
  Algorithms/Searching & Sorting/Bubble Sort/bubble_sort.py
Labels: Hacktoberfest, Not assigned to an issue

#136 I have added the BubbleSort in Python language.
  Algorithms/Searching & Sorting/Bubble Sort/BubbleSort.py
  Algorithms/Searching & Sorting/QuickSort/QuickSort.java
  Algorithms/Searching & Sorting/QuickSort/quicksort.java
Labels: Conflict, Hacktoberfest, Not assigned to an issue

#135 Adding selection sort in C
  Algorithms/Searching & Sorting/Selection Sort/selectionsort.c
Labels: Hacktoberfest, Not assigned to an issue

#141 added bubbleSort.cpp
  Algorithms/Searching & Sorting/Bubble Sort/bubbleSort.cpp
Labels: Hacktoberfest, Not assigned to an issue

#170 Binarysearch tree
  Binarysearch tree
  stack in python
Labels: Hacktoberfest, Not assigned to an issue

#172 Binary Search Tree and traversal in python
  Algorithms/Tree Traversal/Binary Search Tree/BST.py
Labels: Hacktoberfest, Not assigned to an issue

#174 STACK
  STACK
Labels: Hacktoberfest, Not assigned to an issue

#183 Update selectionsort.py
  Algorithms/Searching & Sorting/Merge Sort/MergeSort.java
  Algorithms/Searching & Sorting/Selection Sort/selectionsort.py
Labels: Hacktoberfest, Not assigned to an issue

#184 Singly Linked List in CPP
  Data Structures/Singly Linked List/CPP/singlylinkedlist.cpp
Labels: Hacktoberfest, Not assigned to an issue

#185 Fibonacci Series in java
  Algorithms/Maths/Fibonacci series/Java/Fibonacci.java
  Company Specific Interview Questions/Airbnb/Solutions/Java/ValidParantheses.Java
Labels: Hacktoberfest, Not assigned to an issue

#193 Add bubble sort
  Algorithms/Searching & Sorting/Bubble Sort/bubble_sort.java
Labels: Hacktoberfest, Not assigned to an issue

#194 stack
  dfs
  dll
  stack
  tree traversal
Labels: Hacktoberfest, Not assigned to an issue

#197 [Data Structure] Stack Implementation [Python]
  Data Structures/Stack/Python/python_stack_implementation.py
Labels: Hacktoberfest, Not assigned to an issue

#201 [Algo] Perfect Number [C]
  Algorithms/Maths/Perfect number/C/perfect_number.c
Labels: Hacktoberfest, Not assigned to an issue

#202 [Data Structure] Singly Linked List [Python]
  Data Structures/Singly Linked List/Python/linked_list.py
Labels: Hacktoberfest

#206 add bubble sort in java
  Algorithms/Searching & Sorting/Bubble Sort in Java/BubbleSort.java
Labels: Hacktoberfest, Not assigned to an issue

#210 added armstrong-number.py in algorithms/maths/armstrong-number to che…
  Algorithms/Maths/armstrong-number/armstrong-number.py
  README.md
Labels: Conflict, Hacktoberfest, Not assigned to an issue

#212 Binary insert and bubble search algorithm
  Algorithms/Searching & Sorting/Binary Search/Binary_Burbble_Search.cpp
Labels: Hacktoberfest, Not assigned to an issue

#224 Add selectionsort.cpp
  Algorithms/Searching & Sorting/Selection Sort/selectionsort.cpp
Labels: Hacktoberfest, Not assigned to an issue

#248 Selection sort added
  Algorithms/Searching & Sorting/Selection Sort/selectionsort.cpp
Labels: Hacktoberfest, question

#249 Added Bubble Sort Implementation in C
  Algorithms/Searching & Sorting/Bubble Sort/bubble_sort.c
  README.md
Labels: Hacktoberfest, Not assigned to an issue

#252 Belmann Ford algorithm
  Algorithms/Graphs/Belmon Ford Algorithm/CPP/belmonford.c
Labels: Hacktoberfest, question

#264 Added Heap Sort Implementation in C
  Algorithms/Searching & Sorting/Heap Sort/heap_sort.c
  README.md
Labels: Hacktoberfest, Not assigned to an issue

#272 Added a Bubble Sort Algorithm in java
  .gitignore
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/.vs/BubbleSort/v16/.suo
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/.vs/BubbleSort/v16/Server/sqlite3/db.lock
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/.vs/BubbleSort/v16/Server/sqlite3/storage.ide
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/BubbleSort.sln
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/BubbleSort/App.config
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/BubbleSort/BubbleSort.csproj
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/BubbleSort/Program.cs
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/BubbleSort/Properties/AssemblyInfo.cs
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/BubbleSort/obj/Debug/BubbleSort.csproj.CoreCompileInputs.cache
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/BubbleSort/obj/Debug/BubbleSort.csprojAssemblyReference.cache
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/BubbleSort/BubbleSort/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/build.xml
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/manifest.mf
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/nbproject/build-impl.xml
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/nbproject/genfiles.properties
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/nbproject/project.properties
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/nbproject/project.xml
  Algorithms/Searching & Sorting/Bubble Sort/Bubble Sort/src/bubble/sort/BubbleSort.java
  Data Structures/Queue/Python/Queue.py
Labels: Hacktoberfest, Not assigned to an issue

#276 added findHeight.cpp
  Algorithms/Tree/Height of the tree/CPP/findHeight.cpp
  Algorithms/Tree/Height of the tree/CPP/readme.md
Labels: Conflict, Hacktoberfest, Not assigned to an issue

#281 - Add Algorithm Sieve Eratosthenes Cpp
  Algorithms/Maths/Sieve Eratosthenes/CPP/SieveEratosthenes.cpp
  Algorithms/Maths/Sieve Eratosthenes/CPP/sieve
Labels: Hacktoberfest, Not assigned to an issue

#295 Numbers
  Algorithms/Maths/Perfect Number/perfectno.cpp
  perfectnumber.c
  string.cpp
Labels: Hacktoberfest, question

#300 Shell Sort In C++ Added
  Algorithms/Graphs/Floyd-Warshall Algorithm/CPP/FW.cpp
  Algorithms/Graphs/Floyd-Warshall Algorithm/CPP/a.out
  Algorithms/Maths/Magic Number/MagicNo.py
  Algorithms/Maths/Pallindrome number/C/Palindrome.c
  Data Structures/ShellSort.cpp
Labels: Hacktoberfest, Not assigned to an issue

#354 C++ code to find factorial of big numbers
  Algorithms/Maths/Perfect Number/perfectno.cpp
Labels: Hacktoberfest

#314 Added linear search implementation in Java
  Algorithms/Searching & Sorting/Linear Search/LinearSearch.java
Labels: Hacktoberfest, Not assigned to an issue

#316 please check out this program to test if a no. is perfect or not
  Algorithms/Maths/Perfect Number/a.out
  Algorithms/Maths/Perfect Number/perfect number.c
Labels: Hacktoberfest, Not assigned to an issue

#317 QuickSort_2.py
  Algorithms/Searching & Sorting/QuickSort/QuickSort_2.py
Labels: Hacktoberfest, Not assigned to an issue

#319 added new Data Structure Circular Queue
  Data Structures/Circular Queue/C/circular-queue.c
  README.md
Labels: Hacktoberfest, Not assigned to an issue

#334 Catalan numbers programs in c++ and python
  Algorithms/Maths/Catalan number/catalan_no.c
  Algorithms/Maths/Catalan number/catalan_num.py
Labels: Hacktoberfest, question

#345 Added Sieve of Eratosthenes to generate prime numbers
  Algorithms/Eratosthenes.cpp
Labels: Hacktoberfest, Not assigned to an issue

#346 insertion.py added.
  Algorithms/Searching & Sorting/insertion.py
Labels: Hacktoberfest, Not assigned to an issue

#357 added floyd warshal algo in java
  Algorithms/Graph Traversal/Floyd-Warshall Algorithm/floyd_warshal.java
Labels: Hacktoberfest

#362 Mazepath Algorithm in Java #361
  Algorithms/Arrays/Mazepath/mazepath.java
Labels: Hacktoberfest

#383 fibonacci.py: Add Algorithm for Fibonacci Series
  Algorithms/fibonacci.py
Labels: Hacktoberfest

#359 My new feature4
  Algorithms/Searching & Sorting/Bubble Sort/bubble_sort.java
Labels: Hacktoberfest

#392 Validparentheses.cpp: Add Airbnb Valid parenthesis
  Company Specific Interview Questions/Airbnb/Solutions/Cpp/Validparentheses.cpp
Labels: Hacktoberfest

#396 Create height_tree.py
  Algorithms/Tree/Height of the tree/Python/height_tree.py
Labels: Hacktoberfest

#397 fixed a faulty algo and readme
  .DS_Store
  README.md
Labels: Hacktoberfest

#399 Create priority_queue.py
  Data Structures/Priority Queue/Python/priority_queue.py
Labels: Hacktoberfest

#400 Added Bubble Sort Java code in Arrays Directory
  Algorithms/Arrays/Bubble_sort/SortBubble.java
Labels: Hacktoberfest

#402 Add Python stack implementation
  Data Structures/Stack/Python/Stack.py
Labels: Hacktoberfest

#403 Create Heapsort.c
  Algorithms/Searching & Sorting/Heap Sort/Heapsort.c
Labels: Hacktoberfest

#404 Create countingsort.py
  Algorithms/Searching & Sorting/Counting Sort/countingsort.py
Labels: Hacktoberfest

#406 function for height of bst
  Algorithms/Tree/Height of the tree/Java/bst_height.java
  Algorithms/Tree/Height of the tree/Java/readme.md
Labels: Hacktoberfest

#408 Create countingsort in python
  Algorithms/Searching & Sorting/Counting Sort/python
Labels: Hacktoberfest

#410 Create Radixsort.py
  Algorithms/Searching & Sorting/Radix Sort/Radixsort.py
Labels: Hacktoberfest

#412 Create Bubblesort.java
  Algorithms/Searching & Sorting/Bubble Sort/Bubblesort.java
Labels: Hacktoberfest

#413 Create linearsearch.java
  Algorithms/Searching & Sorting/Linear Search/linearsearch.java
Labels: Hacktoberfest

#419 Fix #380
  Algorithms/sumofsubset.py
Labels: Hacktoberfest

#420 Fix #379
  Algorithms/fibonacci.py
Labels: Hacktoberfest

#421 added fibonacci in Python in one line
  fibonacci.py
Labels: Hacktoberfest

#428 Create insertion_sort.py
  Algorithms/Searching & Sorting/Insertion Sort/insertion_sort.py
Labels: Hacktoberfest

#429 pancake sorting
  pancakesort.py
Labels: Hacktoberfest

#430 added Fibonacci in C
  Fibbonacci.c
Labels: Hacktoberfest

#431 CircularSinglyLinkedList.java
  Data Structures/Circular Linked List/Java/CircularSinglyLinkedList.java
Labels: Hacktoberfest

#432 Update README.md
  README.md
Labels: Hacktoberfest

#434 [Algorithm] Bogo Sort [Python]
  Algorithms/Searching & Sorting/Bogo Sort/bogo.py
Labels: Hacktoberfest

#437 Create solve_sudoku
  Company Specific Interview Questions/Amazon/Solutions/Cpp/solve_sudoku
Labels: Hacktoberfest

#438 Create merge_arrays_without_extra_space
  Company Specific Interview Questions/Amazon/Solutions/Cpp/merge_without_extra_space.c
Labels: Hacktoberfest

#439 Add some feature
  Algorithms/Searching & Sorting/Insertion Sort/Insertion-Sort.c
Labels: Hacktoberfest

#445 Add Priority Queue implementation in Java resolving #220
  Data Structures/Priority Queue/Java/Main.java
Labels: Hacktoberfest

#447 added shell sort python program
  Algorithms/Searching & Sorting/Shell Sort/shellsort.py
Labels: Hacktoberfest

#449 [Readme] Add DP table
  README.md
Labels: Hacktoberfest

#450 BST changes
  Algorithms/Tree Traversal/Binary Search Tree/Python/1.Search.py
  Algorithms/Tree Traversal/Binary Search Tree/Python/2.Insert.py
Labels: Hacktoberfest

#451 Fractional_knapsack_problem in cpp
  Algorithms/Dynamic Programming/Fractional_Knapsack_Problem.cpp
Labels: Hacktoberfest

#452 Added Shell Sort
  Algorithms/Searching & Sorting/Shell Sort/sort.py
Labels: Hacktoberfest

#453 Added Bogo Sort
  Algorithms/Searching & Sorting/Bogo Sort/sort.py
Labels: Hacktoberfest

#454 Greedy algorithm
  Algorithms/Dynamic Programming/Fractional_Knapsack_Problem.cpp
  Algorithms/Greedy Algorithm/README.md
Labels: Hacktoberfest
